<?php

namespace Database\Seeders;

use App\Models\Video;
use Illuminate\Database\Seeder;

class VideoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $videos = [
            [
                'id_youtube' => 'dQw4w9WgXcQ',
                'title' => 'Never Gonna Give You Up',
                'description' => 'Official music video for "Never Gonna Give You Up" by Rick Astley',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF0000/FFFFFF?text=Never+Gonna+Give+You+Up',
                'duration' => 212,
                'band_name' => 'Rick Astley',
                'region' => 'UK',
            ],
            [
                'id_youtube' => '9bZkp7q19f0',
                'title' => 'Gangnam Style',
                'description' => 'Psy - GANGNAM STYLE 강남스타일 M/V',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/00FF00/FFFFFF?text=Gangnam+Style',
                'duration' => 252,
                'band_name' => 'PSY',
                'region' => 'South Korea',
            ],
            [
                'id_youtube' => 'kJQP7kiw5Fk',
                'title' => 'Despacito',
                'description' => 'Luis Fonsi - Despacito ft. Daddy Yankee',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/0000FF/FFFFFF?text=Despacito',
                'duration' => 279,
                'band_name' => 'Luis Fonsi',
                'region' => 'Puerto Rico',
            ],
            [
                'id_youtube' => 'hT_nvWreIhg',
                'title' => 'Uptown Funk',
                'description' => 'Mark Ronson - Uptown Funk ft. Bruno Mars',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FFD700/000000?text=Uptown+Funk',
                'duration' => 270,
                'band_name' => 'Mark Ronson',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'YQHsXMglC9A',
                'title' => 'Hello',
                'description' => 'Adele - Hello',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/800080/FFFFFF?text=Hello',
                'duration' => 361,
                'band_name' => 'Adele',
                'region' => 'UK',
            ],
            [
                'id_youtube' => 'CevxZvSJLk8',
                'title' => 'Wrecking Ball',
                'description' => 'Miley Cyrus - Wrecking Ball',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF69B4/FFFFFF?text=Wrecking+Ball',
                'duration' => 231,
                'band_name' => 'Miley Cyrus',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'kYtGl1dX5qI',
                'title' => 'Roar',
                'description' => 'Katy Perry - Roar',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FFA500/FFFFFF?text=Roar',
                'duration' => 243,
                'band_name' => 'Katy Perry',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'LsoKjdvwU_o',
                'title' => 'Stressed Out',
                'description' => 'Twenty One Pilots - Stressed Out',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/8B4513/FFFFFF?text=Stressed+Out',
                'duration' => 200,
                'band_name' => 'Twenty One Pilots',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'QGJuMBdaqIw',
                'title' => 'Sugar',
                'description' => 'Maroon 5 - Sugar',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF1493/FFFFFF?text=Sugar',
                'duration' => 235,
                'band_name' => 'Maroon 5',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'kfVsfOSbJY0',
                'title' => 'Lean On',
                'description' => 'Major Lazer & DJ Snake - Lean On ft. MØ',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/00CED1/FFFFFF?text=Lean+On',
                'duration' => 178,
                'band_name' => 'Major Lazer',
                'region' => 'USA',
            ],
            [
                'id_youtube' => '47dtFZ8CFo8',
                'title' => 'Sorry',
                'description' => 'Justin Bieber - Sorry',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FFB6C1/000000?text=Sorry',
                'duration' => 200,
                'band_name' => 'Justin Bieber',
                'region' => 'Canada',
            ],
            [
                'id_youtube' => 'wcVNlyvqvj0',
                'title' => 'Dark Horse',
                'description' => 'Katy Perry - Dark Horse ft. Juicy J',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/9400D3/FFFFFF?text=Dark+Horse',
                'duration' => 215,
                'band_name' => 'Katy Perry',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'kyOJOR6gl7o',
                'title' => 'Blank Space',
                'description' => 'Taylor Swift - Blank Space',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FFC0CB/000000?text=Blank+Space',
                'duration' => 242,
                'band_name' => 'Taylor Swift',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'IPXIgEAGe4U',
                'title' => 'Counting Stars',
                'description' => 'OneRepublic - Counting Stars',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/4169E1/FFFFFF?text=Counting+Stars',
                'duration' => 254,
                'band_name' => 'OneRepublic',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'RgKAFK5djSk',
                'title' => 'Happy',
                'description' => 'Pharrell Williams - Happy',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FFD700/000000?text=Happy',
                'duration' => 233,
                'band_name' => 'Pharrell Williams',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'OpQFFLBmPIk',
                'title' => 'All About That Bass',
                'description' => 'Meghan Trainor - All About That Bass',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF69B4/FFFFFF?text=All+About+That+Bass',
                'duration' => 197,
                'band_name' => 'Meghan Trainor',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'nu6lsQlYZcE',
                'title' => 'Shake It Off',
                'description' => 'Taylor Swift - Shake It Off',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF1493/FFFFFF?text=Shake+It+Off',
                'duration' => 242,
                'band_name' => 'Taylor Swift',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'IcrbM1l_BoI',
                'title' => 'Animals',
                'description' => 'Maroon 5 - Animals',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/8B0000/FFFFFF?text=Animals',
                'duration' => 226,
                'band_name' => 'Maroon 5',
                'region' => 'USA',
            ],
            [
                'id_youtube' => '0KSOMA3QBU0',
                'title' => 'Rude',
                'description' => 'MAGIC! - Rude',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF8C00/FFFFFF?text=Rude',
                'duration' => 210,
                'band_name' => 'MAGIC!',
                'region' => 'Canada',
            ],
            [
                'id_youtube' => 'S9uTntt26AU',
                'title' => 'Problem',
                'description' => 'Ariana Grande - Problem ft. Iggy Azalea',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FFDAB9/000000?text=Problem',
                'duration' => 203,
                'band_name' => 'Ariana Grande',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'kLTTSPitDzQ',
                'title' => 'Waves',
                'description' => 'Mr Probz - Waves',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/1E90FF/FFFFFF?text=Waves',
                'duration' => 184,
                'band_name' => 'Mr Probz',
                'region' => 'Netherlands',
            ],
            [
                'id_youtube' => 'o1tI2flJ-54',
                'title' => 'Turn Down for What',
                'description' => 'Lil Jon & DJ Snake - Turn Down for What',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF4500/FFFFFF?text=Turn+Down+for+What',
                'duration' => 198,
                'band_name' => 'Lil Jon',
                'region' => 'USA',
            ],
            [
                'id_youtube' => '5GL9OlHqgzw',
                'title' => 'Fancy',
                'description' => 'Iggy Azalea - Fancy ft. Charli XCX',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FFB6C1/000000?text=Fancy',
                'duration' => 199,
                'band_name' => 'Iggy Azalea',
                'region' => 'Australia',
            ],
            [
                'id_youtube' => 'sENM2wA_-Gg',
                'title' => 'Chandelier',
                'description' => 'Sia - Chandelier',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/DDA0DD/FFFFFF?text=Chandelier',
                'duration' => 216,
                'band_name' => 'Sia',
                'region' => 'Australia',
            ],
            [
                'id_youtube' => 'lWA2pjMjpVs',
                'title' => 'Am I Wrong',
                'description' => 'Nico & Vinz - Am I Wrong',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/87CEEB/000000?text=Am+I+Wrong',
                'duration' => 244,
                'band_name' => 'Nico & Vinz',
                'region' => 'Norway',
            ],
            [
                'id_youtube' => '4cfPtlZhaqc',
                'title' => 'Take Me to Church',
                'description' => 'Hozier - Take Me to Church',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/2F4F4F/FFFFFF?text=Take+Me+to+Church',
                'duration' => 241,
                'band_name' => 'Hozier',
                'region' => 'Ireland',
            ],
            [
                'id_youtube' => 'qRC4Vk6kisI',
                'title' => 'Sing',
                'description' => 'Ed Sheeran - Sing',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF6347/FFFFFF?text=Sing',
                'duration' => 231,
                'band_name' => 'Ed Sheeran',
                'region' => 'UK',
            ],
            [
                'id_youtube' => 'DgufZ1Y99TQ',
                'title' => 'Habits (Stay High)',
                'description' => 'Tove Lo - Habits (Stay High)',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/BA55D3/FFFFFF?text=Habits',
                'duration' => 211,
                'band_name' => 'Tove Lo',
                'region' => 'Sweden',
            ],
            [
                'id_youtube' => 'afWUt1a9S2c',
                'title' => 'Maps',
                'description' => 'Maroon 5 - Maps',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF4500/FFFFFF?text=Maps',
                'duration' => 185,
                'band_name' => 'Maroon 5',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'l40-SvIiEIE',
                'title' => 'Bang Bang',
                'description' => 'Jessie J, Ariana Grande & Nicki Minaj - Bang Bang',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF1493/FFFFFF?text=Bang+Bang',
                'duration' => 189,
                'band_name' => 'Jessie J',
                'region' => 'UK',
            ],
            [
                'id_youtube' => 'pEkJ1UUFlLA',
                'title' => 'Summer',
                'description' => 'Calvin Harris - Summer',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FFD700/000000?text=Summer',
                'duration' => 223,
                'band_name' => 'Calvin Harris',
                'region' => 'Scotland',
            ],
            [
                'id_youtube' => '9A32_27pC3s',
                'title' => 'Love Me Again',
                'description' => 'John Newman - Love Me Again',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/DC143C/FFFFFF?text=Love+Me+Again',
                'duration' => 234,
                'band_name' => 'John Newman',
                'region' => 'UK',
            ],
            [
                'id_youtube' => '0HDdjwpPM3Y',
                'title' => 'Young and Beautiful',
                'description' => 'Lana Del Rey - Young and Beautiful',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/9370DB/FFFFFF?text=Young+and+Beautiful',
                'duration' => 242,
                'band_name' => 'Lana Del Rey',
                'region' => 'USA',
            ],
            [
                'id_youtube' => '69grlHIPrvc',
                'title' => 'Team',
                'description' => 'Lorde - Team',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/483D8B/FFFFFF?text=Team',
                'duration' => 193,
                'band_name' => 'Lorde',
                'region' => 'New Zealand',
            ],
            [
                'id_youtube' => 'VRK_tTIaRsU',
                'title' => 'Demons',
                'description' => 'Imagine Dragons - Demons',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/8B4513/FFFFFF?text=Demons',
                'duration' => 217,
                'band_name' => 'Imagine Dragons',
                'region' => 'USA',
            ],
            [
                'id_youtube' => '6JCLY0Rlx6Q',
                'title' => 'The Monster',
                'description' => 'Eminem - The Monster ft. Rihanna',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/000000/FFFFFF?text=The+Monster',
                'duration' => 325,
                'band_name' => 'Eminem',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'FeA1_stJ2og',
                'title' => 'Best Day of My Life',
                'description' => 'American Authors - Best Day of My Life',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF8C00/FFFFFF?text=Best+Day+of+My+Life',
                'duration' => 196,
                'band_name' => 'American Authors',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'mWRsgZuwhr8',
                'title' => 'Talk Dirty',
                'description' => 'Jason Derulo - Talk Dirty ft. 2 Chainz',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF1493/FFFFFF?text=Talk+Dirty',
                'duration' => 183,
                'band_name' => 'Jason Derulo',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'ko2vBAd9I3k',
                'title' => 'Let Her Go',
                'description' => 'Passenger - Let Her Go',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/696969/FFFFFF?text=Let+Her+Go',
                'duration' => 241,
                'band_name' => 'Passenger',
                'region' => 'UK',
            ],
            [
                'id_youtube' => 'm-M1Atr_5oY',
                'title' => 'Wake Me Up',
                'description' => 'Avicii - Wake Me Up',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FFD700/000000?text=Wake+Me+Up',
                'duration' => 241,
                'band_name' => 'Avicii',
                'region' => 'Sweden',
            ],
            [
                'id_youtube' => 'GnBac2hGfZc',
                'title' => 'Timber',
                'description' => 'Pitbull - Timber ft. Ke$ha',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/228B22/FFFFFF?text=Timber',
                'duration' => 203,
                'band_name' => 'Pitbull',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'Y12cKHMBPpk',
                'title' => 'Thrift Shop',
                'description' => 'Macklemore & Ryan Lewis - Thrift Shop ft. Wanz',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FFD700/000000?text=Thrift+Shop',
                'duration' => 242,
                'band_name' => 'Macklemore',
                'region' => 'USA',
            ],
            [
                'id_youtube' => 'fWNaR-rxAic',
                'title' => 'Can\'t Hold Us',
                'description' => 'Macklemore & Ryan Lewis - Can\'t Hold Us ft. Ray Dalton',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF6347/FFFFFF?text=Can%27t+Hold+Us',
                'duration' => 261,
                'band_name' => 'Macklemore',
                'region' => 'USA',
            ],
            [
                'id_youtube' => '08RjkIq9Fnk',
                'title' => 'Blurred Lines',
                'description' => 'Robin Thicke - Blurred Lines ft. T.I., Pharrell',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF1493/FFFFFF?text=Blurred+Lines',
                'duration' => 253,
                'band_name' => 'Robin Thicke',
                'region' => 'USA',
            ],
            [
                'id_youtube' => '09R8_2xJylo',
                'title' => 'Clarity',
                'description' => 'Zedd - Clarity ft. Foxes',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/00CED1/FFFFFF?text=Clarity',
                'duration' => 262,
                'band_name' => 'Zedd',
                'region' => 'Germany',
            ],
            [
                'id_youtube' => 'k6mFF3VmVAs',
                'title' => 'Love Me Like You Do',
                'description' => 'Ellie Goulding - Love Me Like You Do',
                'thumbnail_url' => 'https://via.placeholder.com/320x180/FF69B4/FFFFFF?text=Love+Me+Like+You+Do',
                'duration' => 233,
                'band_name' => 'Ellie Goulding',
                'region' => 'UK',
            ],
        ];

        foreach ($videos as $video) {
            Video::updateOrCreate(['id_youtube' => $video['id_youtube']], $video);
        }
    }
}
